spring.datasource.url=jdbc:postgresql://localhost:5432/smartcity_dwh
spring.datasource.username=sir_admin
spring.datasource.password=enterprise_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.mongodb.uri=mongodb://localhost:27017/smartcity_raw

# Security disable for dev
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
